# REMOVE THIS FILE BEFORE SUBMITTING PR TO APACHE/BEAM

image: google/cloud-sdk

stages:
  - test

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID

check:
  tags:
    - docker
  stage: test
  rules:
    - when: always
  script:
    - ./gradlew -p sdks/java/io/snowflake check

batchIntegrationTest:
  tags:
    - docker
  stage: test
  rules:
    - if: $CI_MERGE_REQUEST_ID
  script:
    - gcloud auth activate-service-account --key-file $GOOGLE_APPLICATION_CREDENTIALS
    - ./gradlew --info -p sdks/java/io/snowflake integrationTest -DintegrationTestPipelineOptions="[\"--serverName=$SF_HOST\", \"--username=$SF_USERNAME\", \"--password=$SF_PASSWORD\",\"--warehouse=$SF_WAREHOUSE\", \"--numberOfRecords=1000\", \"--role=$SF_ROLE\", \"--database=$SF_DATABASE\", \"--schema=PUBLIC\", \"--stagingBucketName=$SF_BUCKET\", \"--storageIntegration=$SF_STORAGE_INTEGRATION\"]" --tests org.apache.beam.sdk.io.snowflake.test.SnowflakeIOIT -DintegrationTestRunner=direct
